### ISSUE TITLE
🐛 Bug - Disconnects, cannot use

### ISSUE THREAD

**Issue by SentyFunBall** [Valour-Software/Valour#118]
**Describe the bug**
After a X period of time, my client will disconnect, leaving me unable to send new messages, and people somewhat able to see mine. The console says "SignalR has reconnected:" and then the bug happens. Sometimes ii cant even open valour without the issue happening

**To Reproduce**
I dont know if its reproduceable, but:
1. Open valour
2. Use valour
3. Get disconnected
**Expected behavior**
For it to not disconnect randomly.

**Screenshots**
I cant post a screenshot sadly.

**System Information:**
 - OS: Windows 10
 - Valour Platform: Web app.
     - Browser: Google Chrome

**Additional context**
2nd time ive opened an issue about this. Lets hope it gets fixed this time.

**Comment by fruitcake5** [comment]
Are there any errors in the console?

**Comment by SentyFunBall** [comment]
Nope. just "SignalR has reconnected"

**Comment by SpikeViper** [comment]
Issue is due to SignalR not reconnecting hubs during reconnect. Should be fixed in 96fcf0f597abc3f1718d7cdc890de570e72d50b7

**Comment by SentyFunBall** [comment]
Just logged onto valour, disconnected after a few minutes again. Not sure if its my internet, which likes to cut out every once and a while, but its still broken to the point where the platform is unusable for me.

**Comment by SentyFunBall** [comment]
Discard that last comment, im just dumb
